import Head from "next/head";
import Image from "next/image";
import styles from ".src/components/error/boundryule.css";
import Boundry from "src/components/error/boundry";
import React from "react";

export default function Home() {
  React.useEffect(() => {
    countVisitorsOfPage("entry-page", "Bosh sahifa");
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>SoftSells</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
}

export async function getStaticProps() {}
