import Head from "next/head";
import React from "react";
import Services from "src/components/Services";
import Layout from "src/layouts/Layout";
import Contact from "../src/components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SoftSells</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Services />
        <Contact />
      </Layout>
    </div>
  );
}
